version: '3'
services:
  immudb:
    image: codenotary/immudb
    ports:
      - "8080:8080"
      - "3322:3322"
      - "9497:9497"
    volumes:
      - db-data:/var/lib/immudb
  imlogs:
    image: ashirko/imlogs:0.1.5
    ports:
      - "8081:8081"
    depends_on:
      - "immudb"
    environment:
      - DB_HOST=immudb
      - DB_PORT=3322
      - DB_USER=immudb
      - DB_PASSWORD=immudb
      - MAX_DB_CONN_RETRIES=200
      - WEB_SERVER_HOST=0.0.0.0
      - WEB_SERVER_PORT=8081
      - GIN_MODE=release
volumes:
  db-data: